# font
font pango:System San Francisco Display 9

# colors
set $base00 #101218
set $base01 #1f222d
set $base02 #252936
set $base03 #7780a1
set $base04 #C0C5CE
set $base05 #d1d4e0
set $base06 #C9CCDB
set $base07 #ffffff
set $base08 #ee829f
set $base09 #f99170
set $base0A #ffefcc
set $base0B #a5ffe1
set $base0C #97e0ff
set $base0D #97bbf7
set $base0E #c0b7f9
set $base0F #fcc09e

# bar {
#     font pango: System San Francisco Display 10
# 	status_command i3status 
#     position top
#     strip_workspace_numbers no
#     height 28
#     bindsym button4 nop
#     bindsym button5 nop
#     colors {
#       separator $base03
#       background $base01
#       statusline $base05
# #                        border  background text
#       focused_workspace  $base01 $base01    $base07
#       active_workspace   $base01 $base02    $base03
#       inactive_workspace $base01 $base01    $base03
#       urgent_workspace   $base01 $base01    $base08
# 	}
# }

set  $bg-color             #2f343f
set  $inactive-gb-color    #2f343f
set  $text-color           #f3f4f5
set  $inactive-text-color  #676E7D
set  $urgent-bg-color      #E53935
set  $indicator            #00ff00

# window colors
#                        border              background          test                  indicator
#client.focused           $bg-color           $bg-color           $text-color           $indicator
#client.unfocused         $inactive-bg-color  $inactive-bg-color  $inactive-text-color  $indicator
#client.focused_inactive  $inactive-bg-color  $inactive-bg-color  $inactive-text-color  $indicator
#client.urgent            $urgent-gb-color    $urgent-bg-color    $text-color           $indicator
 
  client.focused          #556064 #556064 #80FFF9 #FDF6E3
  client.focused_inactive #2F3D44 #2F3D44 #1ABC9C #454948
  client.unfocused        #2F3D44 #2F3D44 #1ABC9C #454948
  client.urgent           #CB4B16 #FDF6E3 #1ABC9C #268BD2
  client.placeholder      #000000 #0c0c0c #ffffff #000000 

  client.background       #2B2C2B


