# quick app launcher
set $app_picker (w) browser (s) screenshot
mode "$app_picker" {
    bindsym w exec --no-startup-id google-chrome, mode "default"
	bindsym s exec --no-startup-id flameshot gui, mode "default" 

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Shift+d mode "$app_picker"

# Open specific applications in floating mode
for_window [class="^.*"] border pixel 4
for_window [class="Audacity"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="task-dialog"] floating enable
for_window [class="Nautilus"] floating enable
for_window [class="Nautilus"] resize set 2000 1700 

# Open applications on specific workspaces
assign [class="firefox"] $ws2
assign [class="google-chrome(.*)"] $ws2
assign [title="google-chrome(.*)"] $ws8
 
# switch to workspace with urgent window automatically
for_window [urgent=latest] focus

# Set shut down, restart and locking features
bindsym $mod+i mode "$mode_system"
set $mode_system (l)ock, (e)xit, switch_(u)ser, (s)uspend, (h)ibernate, (r)eboot, (Shift+s)hutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id i3exit lock, mode "default"
    bindsym s exec --no-startup-id i3exit suspend, mode "default"
    bindsym u exec --no-startup-id i3exit switch_user, mode "default"
    bindsym e exec --no-startup-id i3exit logout, mode "default"
    bindsym h exec --no-startup-id i3exit hibernate, mode "default"
    bindsym r exec --no-startup-id i3exit reboot, mode "default"
    bindsym Shift+s exec --no-startup-id i3exit shutdown, mode "default"

    # exit system mode: "Enter" or "Escape"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# hide/unhide i3status bar
bindsym $mod+m bar mode toggle

# propagate terminal colors
set_from_resource $term_background background
set_from_resource $term_foreground foreground
set_from_resource $term_color0     color0
set_from_resource $term_color1     color1
set_from_resource $term_color2     color2
set_from_resource $term_color3     color3
set_from_resource $term_color4     color4
set_from_resource $term_color5     color5
set_from_resource $term_color6     color6
set_from_resource $term_color7     color7
set_from_resource $term_color8     color8
set_from_resource $term_color9     color9
set_from_resource $term_color10    color10
set_from_resource $term_color11    color11
set_from_resource $term_color12    color12
set_from_resource $term_color13    color13
set_from_resource $term_color14    color14
set_from_resource $term_color15    color15
