set $app_picker (w) browser (s) screenshot
mode "$app_picker" {
    bindsym w exec --no-startup-id google-chrome, mode "default"
	bindsym s exec --no-startup-id flameshot gui, mode "default" 

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Shift+d mode "$app_picker"

# Open specific applications in floating mode
for_window [class="^.*"] border pixel 4
for_window [class="Audacity"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="task-dialog"] floating enable

# Open applications on specific workspaces
assign [class="firefox"] $ws2
assign [class="google-chrome"] $ws2
 
