
# navigation
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+b split h;exec notify-send -t 800 'tile horizontally'
bindsym $mod+v split v;exec notify-send -t 800 'tile vertically'

# basic commands
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
bindsym $mod+r mode "resize"
bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+bracketleft split h, exec i3-sensible-terminal
bindsym $mod+bracketright split v, exec i3-sensible-terminal
bindsym $mod+Shift+q kill
bindsym $mod+d exec --no-startup-id rofi -show run
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
bindsym $mod+Shift+x exec i3lock
bindsym XF86KbdBrightnessUp   exec xbacklight -inc 10 # increase screen brightness
bindsym XF86KbdBrightnessDown exec xbacklight -dec 10 # decrease screen brightness
bindsym Print exec --no-startup-id flameshot gui  

# layout maniputation
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle
bindsym $mod+f fullscreen toggle
bindsym $mod+a focus parent
#bindsym $mod+d focus child

# resize window (you can also use the mouse for that)
mode "resize" {
    bindsym h resize shrink width 3 px or 3 ppt
    bindsym j resize grow height 3 px or 3 ppt
    bindsym k resize shrink height 3 px or 3 ppt
    bindsym l resize grow width 3 px or 3 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
 
