#!/bin/bash

if ! [ -x "$(command -v stow)" ]; then
  echo 'Error: GNU Stow is not installed.' >&2
  exit 1
fi

STOWDIR=$(cd "$( dirname "$0" )" && pwd)
BACKUPDIR=${SCRIPTDIR}/.backup
PACKAGES=$(find . -mindepth 1 -maxdepth 1 -type d -printf '%P ' | sed -e 's:[.]git::g' -e 's:[.]backup::g')
TARGET=$HOME
STOW=$(which stow)

