#!/bin/bash

if ! [ -x "$(command -v stow)" ]; then
	echo 'Error: GNU Stow is not installed.' >&2
	exit 1
fi

[ $# -eq 0 ] && echo "Usage: ./install <package name>" 1>&2 && exit 1

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
TARGET=$HOME
SOURCE=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
CONFIG="$SOURCE/.stownofolding"
PACKAGES=$@

mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$HOME/.local/bin"
for package in $PACKAGES; do
	package=${package%%+(/)}
	if grep -q -x -F "$package" "$CONFIG"; then
		OPT="--no-folding"
	else
		OPT=""
	fi

	echo "Install $package"
	stow $OPT -vt "$TARGET" "$package"
done
