# config file for TMUX 3.4

# good practice: don't use different aliases for the same command
#   set  --> set-option
#   setw --> set-window-option
#   run  --> run-shell
#   bind --> bind-key
#       -r flag: enable keep hitting bind key without prefix
#       -n flag: enable bind key without prefix
#       -g flag: global

## ============== plugins =================================
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-yank'

source-file -F "#{d:current_file}/config/options.tmux"
source-file -F "#{d:current_file}/config/functions.tmux"
source-file -F "#{d:current_file}/config/keybindings.tmux"


## ============== theme configuration =======================
set -g @catppuccin_flavor 'mocha' # or frappe, macchiato, mocha

set -g @catppuccin_date_time_text "%d-%m-%Y %H:%M"

# window elements
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_default_fill "none" # or 'number' the number is highlighted
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "all" # the number and text field are highlighted
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_right_separator ""


# status elements
set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_status_modules_right "cpu battery date_time"

set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "

set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Install plugins using <prefix> + I
# for more info go to https://github.com/tmux-plugins/tpm
run '~/.config/tmux/plugins/tpm/tpm'

