#!/bin/bash

cd $(git rev-parse --show-toplevel)

{
  # Get files with their status
  git ls-files --others --exclude-standard | sed 's/^/?? /'
  git diff --name-only | sed 's/^/M  /'
  git diff --name-only --staged | sed 's/^/A  /'
} | sort -u | fzf -m --cycle --no-height --header="Select files to add to the staging area" \
  --preview 'git preview-file {}' \
  --preview-window=right:60%:wrap \
  --bind 'ctrl-d:preview-page-down,ctrl-u:preview-page-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up' |
  awk '{print substr($0,4)}' |
  xargs -r -I {} sh -c 'echo "git add {}"; git add "{}"'
