#!/bin/bash -e

if ! git rev-parse --is-inside-work-tree 2>/dev/null 1>&2; then
  echo "This script should not be run inside a git repository."
  exit 1
fi

ROOT_PATH="$(git rev-parse --show-toplevel)"
GIT_PATH="$ROOT_PATH/.git"
GIT_HOOK="$GIT_PATH/hooks/commit-msg"
CUSTOM_HOOKS="$(command cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/../hooks"
CUSTOM_HOOKS=$(command cd "$CUSTOM_HOOKS" && pwd)

mkdir -p "$(dirname '$GIT_HOOK')"

echo "Creating symlink hook from '$GIT_HOOK' to '$CUSTOM_HOOKS/commit-msg'"
rm -f "$GIT_HOOK"
ln -sf "$CUSTOM_HOOKS/commit-msg" "$GIT_HOOK"

chmod +x "$GIT_HOOK"

echo -e "\nYou are all set!"
