#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ge 1 ]]; then
  ID="$1"
else
  ID="$(ticket-pick)"
  [[ -n "$ID" ]] || exit 0
fi

TITLE="$(ticket-title "$ID")"

git checkout -b "$ID"
git config branch."$ID".description "$TITLE"
