#!/bin/bash

cd $(git rev-parse --show-toplevel)

# Function to preview files based on their status
git_preview_file() {
  local line="$@"
  local status=$1
  local file=${@:2}

  if [[ "$status" == "??" ]]; then
    batcat --style=numbers --color=always "$file" 2>/dev/null || cat "$file"
  elif command -v delta &>/dev/null; then
    git diff --color=always -- "$file" | delta --width $(tput cols) --side-by-side
  else
    git diff --color=always --word-diff=color -- "$file"
  fi
}
echo $@
git_preview_file $@
