#!/bin/bash -e

if [[ "$1" == "-v" ]]; then
  LOGLEVEL=debug
  shift
elif [[ "$1" == "-vv" ]]; then
  LOGLEVEL=verbose
  shift
else
  LOGLEVEL=info
fi
[ $LOGLEVEL == "verbose" ] && set -x

ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
ROOT="$DIR"

SRC="$DIR/src"
INSTALL="$SRC/install.sh"
IO="$SRC/io.sh"

# set defaults
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

# setup some directories
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$HOME/.local/bin"

[ -f "$IO" ] && source "$IO" || (echo "Failed to load io" && exit 1)
[ -f "$INSTALL" ] && source "$INSTALL" || (log error "Failed to load install script" && exit 1)

install $1

exit 0
[ $# -ne 1 ] && echo "Usage: ./install <package name>" 1>&2 && exit 1

if ! command -v stow 1>/dev/null; then
  echo 'Error: GNU Stow is not installed.' >&2
  exit 1
fi

PACKAGE=${1%/}
if [ ! -d $PACKAGE ]; then
  echo "Package $PACKAGE not found" 1>&2
  exit 1
fi

function install-stow() {
  local TARGET=$HOME
  local SOURCE=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
  local PACKAGE=$1

  # determine run arguments
  case $PACKAGE in
  "local")
    OPT="--no-folding"
    ;;
  "media")
    OPT="--no-folding"
    SUDO=sudo
    TARGET="/"
    ;;
  *)
    :
    ;;
  esac

  echo "Install $PACKAGE"

  # modify ownership if necessary
  if [[ -n $SUDO ]]; then
    sudo chown -R root:root $PACKAGE
  fi

  # install the pacakge
  $SUDO stow $OPT -vt "$TARGET" "$PACKAGE"

  if [ $? -ne 0 ]; then
    exit 1
  fi
}

function install-post() {
  local PACKAGE=$1

  # determine run arguments
  case $PACKAGE in
  "media")
    install media-post
    ;;
  *)
    :
    ;;
  esac
}

install-stow $PACKAGE

install-post $PACKAGE

case "$1" in
'stow') ;;

'install') ;;
*)
  echo "Usage: $ME <command> [args]:

  Commands                    Description
  --------                    -----------
  stow                        List all stowable packages
  stow <package>              Stow <package> 
  install                     List all installers
  install <installer>         Run the installer

  Examples:

  $ME stow
  $ME stow nvim
  $ME install
  $ME install lynx
  "
  ;;
esac
