#!/bin/bash -e

DEFAULT_BRANCH=$(basename $(git rev-parse --abbrev-ref origin/HEAD) || git branch --sort=-committerdate -l main master | head -1 | sed 's/^[^a-zA-Z]*//')

if [[ -z $DEFAULT_BRANCH ]]; then
  echo "No default branch found." 1>&2
  exit 1
fi

BRANCH=$DEFAULT_BRANCH

if [ $# -eq 1 ]; then
  BRANCH=$1
fi

if [ ! $(git rev-parse --verify $BRANCH 2>/dev/null) ]; then
  echo "Branch '$BRANCH' does not exist." 1>&2
  exit 1
fi

BASE_COMMIT=$(git merge-base $BRANCH HEAD)

if [[ -z $BASE_COMMIT ]]; then
  echo "HEAD has no common base with branch '$BRANCH'." 1>&2
  exit 1
fi

# Go to the repository root
command cd $(git rev-parse --show-toplevel)

# Get current branch name
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Create diff with base commit branch and save it
PATCH=/tmp/pr-diff.patch
git diff $BASE_COMMIT >$PATCH

# Get list of changed files compared to the base commit
CHANGED_FILES=$(git diff --name-only $BASE_COMMIT)

# If no files changed, exit
if [ -z "$CHANGED_FILES" ]; then
  echo "No files have changed"
  exit 1
fi

# Store prompt in temporary file
PROMPT_FILE=$(mktemp)
cat >$PROMPT_FILE <<EOF
> /COPILOT_REVIEW
> #buffers

Please review this PR. Try to use actual code file locations rather than diff line numbers.

focus on the following:

1. Potential bugs or edge cases
2. Code style and best practices
3. Performance considerations
4. Security implications
EOF

# Open nvim with the changed files, the diff, and launch Copilot Chat to review the changes
nvim -R $PATCH $CHANGED_FILES -c "CopilotChat" -c "CopilotChatOpen" -c "r $PROMPT_FILE" -c "stopinsert"

rm $PROMPT_FILE
